---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- push_branch: "*"
  workflow: pipeline_main
- pull_request_source_branch: "*"
  workflow: pipeline_main
- tag: "*"
  workflow: pipeline_main
pipelines:
  pipeline_all:
    stages:
    - stage_1: {}
    - stage_2: {}
    - stage_3: {}
stages:
  stage_1:
    workflows:
    - pipeline_main: {}
  stage_2:
    workflows:
    - tests_1: {}
    - tests_2: {}
    - tests_3: {}
    - tests_4: {}
    - tests_5: {}
  stage_3:
    workflows:
    - deploy: {}
workflows:
  deploy:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_2.*
    - script@1.1:
        title: Deploy Artifacts
        inputs:
        - content: "#!/usr/bin/env bash\nset -euxo pipefail\n\necho \"==== MOVE FILES
            TO DEPLOY DIR ====\"\n\necho \"$BITRISE_ARTIFACT_PATHS\"\n\ncd /tmp\nMYDIR=`pwd`/tmp/Users/vagrant/git/xcodebuild.xcresult\n\ni=1\n\nIFS='|'
            read -ra FILES <<< \"$BITRISE_ARTIFACT_PATHS\"\n\nfor f in ${FILES[@]}\ndo\n
            \ if [ \"${f: -4}\" = \".zip\" ]; then\n    echo \"Processing $f\"\n\n
            \   rm -f -r tmp\n    mkdir tmp\n    unzip \"$f\" -d tmp\n\n    echo \"--Trainer--\"\n\n
            \   mkdir \"${BITRISE_TEST_RESULT_DIR}/test_${i}\"\n\n    trainer \\\n
            \   --path \"${MYDIR}\" \\\n    --output_directory \"${BITRISE_TEST_RESULT_DIR}/test_${i}\"
            \\\n    || :\n\n    echo \\\n      \"{ \\\"test-name\\\": \\\"Tests ${i}\\\"
            }\" > \\\n      \"${BITRISE_TEST_RESULT_DIR}/test_${i}/test-info.json\"\n\n
            \   ((i++))\n    \n  fi\ndone"
    - deploy-to-bitrise-io@2: {}
  pipeline_main:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6: {}
    - cocoapods-install@2: {}
    - git::https://github.com/DamienBitrise/bitrise-test-plan-sharder.git@master:
        title: Bitrise Test Plan Sharder
        inputs:
        - xcode_project: Notes.xcodeproj
        - target: NotesUITests
        - shards: '5'
        - scheme: Notes
        - test_plan: Notes.xctestplan
        - debug_mode: 'true'
        - test_path: ''
        - file_type: ".swift"
    - script@1.1:
        title: Build for Testing
        inputs:
        - content: |+
            set -euxo pipefail
            echo "-- build-for-testing --"

            mkdir DerivedData

            xcodebuild \
            -scheme "Notes" \
            -workspace "Notes.xcworkspace" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" \
            -derivedDataPath "${BITRISE_SOURCE_DIR}/DerivedData" \
            build-for-testing

    - script@1.1:
        title: Compress Derived Data
        is_always_run: true
        inputs:
        - content: |
            set -euxo pipefail
            echo "-- compress --"

            exec zip -0 -qr \
                "${BITRISE_SOURCE_DIR}/DerivedData.zip" \
                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug-iphonesimulator/Notes.app" \
                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug-iphonesimulator/NotesUITests-Runner.app" \
                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Notes_Notes_iphonesimulator13.5-x86_64.xctestrun" \
                "$BITRISE_SOURCE_DIR/Notes.xcworkspace" \
                "$BITRISE_SOURCE_DIR/Notes.xcodeproj" \
                "$BITRISE_SOURCE_DIR/Notes.xctestplan" \
                "$BITRISE_SOURCE_DIR/TestShard_0.xctestplan" \
                "$BITRISE_SOURCE_DIR/TestShard_1.xctestplan" \
                "$BITRISE_SOURCE_DIR/TestShard_2.xctestplan" \
                "$BITRISE_SOURCE_DIR/TestShard_3.xctestplan" \
                "$BITRISE_SOURCE_DIR/TestShard_4.xctestplan"
    - deploy-to-bitrise-io@2:
        inputs:
        - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
    before_run: []
  tests_1:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_1.*
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail

            echo "$BITRISE_ARTIFACT_PATHS"

            echo "-- unzip -- "

            exec unzip "${BITRISE_ARTIFACT_PATHS}"
    - script@1.1:
        title: Test without Building
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\nrm Notes.xctestplan\n\ncp
            TestShard_0.xctestplan Notes.xctestplan\n\nchmod 644 Notes.xctestplan\n\necho
            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-testPlan
            \"Notes\" \\\n-parallel-testing-enabled YES \\\n-maximum-parallel-testing-workers
            $SIMS \\\n-destination \"platform=iOS Simulator,name=iPhone 8,OS=latest\"
            \\\ntest-without-building\n\n"
    - script@1.1:
        title: Compress Result Bundle
        is_always_run: true
        inputs:
        - content: |-
            set -euxo pipefail
            echo "-- compress --"

            cd "${BITRISE_DEPLOY_DIR}/"

            exec zip -qr \
                "${BITRISE_DEPLOY_DIR}/TestResults1.zip" \
                "/Users/vagrant/git/xcodebuild.xcresult"
    - deploy-to-bitrise-io@2: {}
    before_run: []
  tests_2:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_1.*
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail

            echo "$BITRISE_ARTIFACT_PATHS"

            echo "-- unzip -- "

            exec unzip "${BITRISE_ARTIFACT_PATHS}"
    - script@1.1:
        title: Test without Building
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\nrm Notes.xctestplan\n\ncp
            TestShard_1.xctestplan Notes.xctestplan\n\nchmod 644 Notes.xctestplan\n\necho
            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-testPlan
            \"Notes\" \\\n-parallel-testing-enabled YES \\\n-maximum-parallel-testing-workers
            $SIMS \\\n-destination \"platform=iOS Simulator,name=iPhone 8,OS=latest\"
            \\\ntest-without-building\n"
    - script@1.1:
        title: Compress Result Bundle
        is_always_run: true
        inputs:
        - content: |-
            set -euxo pipefail
            echo "-- compress --"

            cd "${BITRISE_DEPLOY_DIR}/"

            exec zip -qr \
                "${BITRISE_DEPLOY_DIR}/TestResults2.zip" \
                "/Users/vagrant/git/xcodebuild.xcresult"
    - deploy-to-bitrise-io@2: {}
    before_run: []
  tests_3:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_1.*
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail

            echo "$BITRISE_ARTIFACT_PATHS"

            echo "-- unzip -- "

            exec unzip "${BITRISE_ARTIFACT_PATHS}"
    - script@1.1:
        title: Test without Building
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
            log\nset -x \n\nmv ./Users/vagrant/git/* .\n\nrm Notes.xctestplan\n\ncp
            TestShard_2.xctestplan Notes.xctestplan\n\nchmod 644 Notes.xctestplan\n\necho
            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-testPlan
            \"Notes\" \\\n-parallel-testing-enabled YES \\\n-maximum-parallel-testing-workers
            $SIMS \\\n-destination \"platform=iOS Simulator,name=iPhone 8,OS=latest\"
            \\\ntest-without-building\n"
    - script@1.1:
        title: Compress Result Bundle
        is_always_run: true
        inputs:
        - content: |-
            set -euxo pipefail
            echo "-- compress --"

            cd "${BITRISE_DEPLOY_DIR}/"

            exec zip -qr \
                "${BITRISE_DEPLOY_DIR}/TestResults3.zip" \
                "/Users/vagrant/git/xcodebuild.xcresult"
    - deploy-to-bitrise-io@2: {}
    before_run: []
  tests_4:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_1.*
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail

            echo "$BITRISE_ARTIFACT_PATHS"

            echo "-- unzip -- "

            exec unzip "${BITRISE_ARTIFACT_PATHS}"
    - script@1.1:
        title: Test without Building
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
            log\nset -x \n\nmv ./Users/vagrant/git/* .\n\nrm Notes.xctestplan\n\ncp
            TestShard_3.xctestplan Notes.xctestplan\n\nchmod 644 Notes.xctestplan\n\necho
            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-testPlan
            \"Notes\" \\\n-parallel-testing-enabled YES \\\n-maximum-parallel-testing-workers
            $SIMS \\\n-destination \"platform=iOS Simulator,name=iPhone 8,OS=latest\"
            \\\ntest-without-building\n"
    - script@1.1:
        title: Compress Result Bundle
        is_always_run: true
        inputs:
        - content: |-
            set -euxo pipefail
            echo "-- compress --"

            cd "${BITRISE_DEPLOY_DIR}/"

            exec zip -qr \
                "${BITRISE_DEPLOY_DIR}/TestResults4.zip" \
                "/Users/vagrant/git/xcodebuild.xcresult"
    - deploy-to-bitrise-io@2: {}
    before_run: []
  tests_5:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: stage_1.*
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail

            echo "$BITRISE_ARTIFACT_PATHS"

            echo "-- unzip -- "

            exec unzip "${BITRISE_ARTIFACT_PATHS}"
    - script@1.1:
        title: Test without Building
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
            log\nset -x \n\nmv ./Users/vagrant/git/* .\n\nrm Notes.xctestplan\n\ncp
            TestShard_4.xctestplan Notes.xctestplan\n\nchmod 644 Notes.xctestplan\n\necho
            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-testPlan
            \"Notes\" \\\n-parallel-testing-enabled YES \\\n-maximum-parallel-testing-workers
            $SIMS \\\n-destination \"platform=iOS Simulator,name=iPhone 8,OS=latest\"
            \\\ntest-without-building\n"
    - script@1.1:
        title: Compress Result Bundle
        is_always_run: true
        inputs:
        - content: |-
            set -euxo pipefail
            echo "-- compress --"

            cd "${BITRISE_DEPLOY_DIR}/"

            exec zip -qr \
                "${BITRISE_DEPLOY_DIR}/TestResults5.zip" \
                "/Users/vagrant/git/xcodebuild.xcresult"
    - deploy-to-bitrise-io@2: {}
    before_run: []
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: Notes.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME: Notes
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: development
  - opts:
      is_expand: false
    SIMS: '2'
meta:
  bitrise.io:
    stack: osx-xcode-13.1.x
    machine_type_id: g2.12core
